package notify

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"
)

// DigestItem represents a single notification event collected for digest delivery.
type DigestItem struct {
	Time    time.Time
	WorkID  string
	Title   string
	Event   string // done / failed / check_pass / check_fail
	Summary string
}

// DigestCollector accumulates notification events and flushes them as a single
// HTML digest email. Thread-safe.
type DigestCollector struct {
	mu     sync.Mutex
	items  []DigestItem
	apiKey string
	to     string
}

// NewDigestCollector creates a DigestCollector that sends to the given address.
// apiKey and to may be empty strings; Flush() is a no-op when either is absent.
func NewDigestCollector(apiKey, to string) *DigestCollector {
	return &DigestCollector{apiKey: apiKey, to: to}
}

// Collect enqueues a notification event for the next Flush.
func (d *DigestCollector) Collect(item DigestItem) {
	if item.Time.IsZero() {
		item.Time = time.Now()
	}
	d.mu.Lock()
	d.items = append(d.items, item)
	d.mu.Unlock()
}

// Flush sends a digest email for all collected items and clears the queue.
// Returns immediately (no-op) if there are no items or credentials are absent.
func (d *DigestCollector) Flush(ctx context.Context) {
	d.mu.Lock()
	if len(d.items) == 0 {
		d.mu.Unlock()
		return
	}
	batch := make([]DigestItem, len(d.items))
	copy(batch, d.items)
	d.items = d.items[:0]
	d.mu.Unlock()

	apiKey := d.apiKey
	to := d.to
	if apiKey == "" || to == "" {
		return
	}

	subject := fmt.Sprintf("[FASE] digest: %d event(s)", len(batch))
	html := buildDigestHTML(batch)
	SendEmail(ctx, apiKey, to, subject, html, nil)
}

// buildDigestHTML renders a summary HTML email for a slice of DigestItems.
func buildDigestHTML(items []DigestItem) string {
	var sb strings.Builder

	sb.WriteString(`<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>FASE Digest</title>
</head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<div style="max-width:600px;margin:0 auto;padding:24px 16px;">
  <div style="background:#ffffff;border-radius:8px;border:1px solid #e5e7eb;overflow:hidden;">
    <div style="background:#1f2937;padding:20px 24px;">
      <h1 style="margin:0;color:#ffffff;font-size:20px;font-weight:600;">FASE Digest</h1>
      <p style="margin:6px 0 0;color:#9ca3af;font-size:13px;">`)
	fmt.Fprintf(&sb, "%d event(s) · %s", len(items), time.Now().UTC().Format("2006-01-02 15:04 UTC"))
	sb.WriteString(`</p>
    </div>
    <div style="padding:20px 24px;">
      <table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr style="border-bottom:2px solid #e5e7eb;">
            <th style="text-align:left;padding:8px 12px 8px 0;font-size:12px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Time</th>
            <th style="text-align:left;padding:8px 12px 8px 0;font-size:12px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Event</th>
            <th style="text-align:left;padding:8px 0;font-size:12px;color:#6b7280;font-weight:600;text-transform:uppercase;letter-spacing:.05em;">Work</th>
          </tr>
        </thead>
        <tbody>`)

	for _, item := range items {
		badgeColor, badgeBg := eventBadgeStyle(item.Event)
		timeStr := item.Time.UTC().Format("15:04:05")

		sb.WriteString(`<tr style="border-bottom:1px solid #f3f4f6;">`)
		fmt.Fprintf(&sb, `<td style="padding:10px 12px 10px 0;font-size:12px;color:#6b7280;white-space:nowrap;">%s</td>`, escapeHTMLDigest(timeStr))
		fmt.Fprintf(&sb, `<td style="padding:10px 12px 10px 0;"><span style="display:inline-block;padding:2px 8px;border-radius:9999px;font-size:11px;font-weight:600;background:%s;color:%s;">%s</span></td>`, badgeBg, badgeColor, escapeHTMLDigest(item.Event))
		sb.WriteString(`<td style="padding:10px 0;">`)
		fmt.Fprintf(&sb, `<div style="font-size:13px;color:#1f2937;font-weight:500;">%s</div>`, escapeHTMLDigest(item.Title))
		if item.WorkID != "" {
			fmt.Fprintf(&sb, `<div style="font-size:11px;color:#9ca3af;margin-top:2px;">%s</div>`, escapeHTMLDigest(item.WorkID))
		}
		if item.Summary != "" {
			fmt.Fprintf(&sb, `<div style="font-size:12px;color:#6b7280;margin-top:4px;">%s</div>`, escapeHTMLDigest(item.Summary))
		}
		sb.WriteString(`</td></tr>`)
	}

	sb.WriteString(`</tbody>
      </table>
    </div>
    <div style="padding:14px 24px;background:#f9fafb;border-top:1px solid #e5e7eb;">
      <p style="margin:0;font-size:11px;color:#9ca3af;">Generated by FASE · Hourly digest</p>
    </div>
  </div>
</div>
</body>
</html>`)

	return sb.String()
}

// eventBadgeStyle returns text and background colours for a digest event type.
func eventBadgeStyle(event string) (textColor, bgColor string) {
	switch event {
	case "done", "check_pass":
		return "#166534", "#dcfce7"
	case "failed", "check_fail":
		return "#991b1b", "#fee2e2"
	default:
		return "#1f2937", "#f3f4f6"
	}
}

// escapeHTMLDigest escapes HTML special characters.
func escapeHTMLDigest(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, `"`, "&#34;")
	return s
}
